crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from todo import views as vws

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    url('^$', vws.index, name="home"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'todo'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/(?P<id>\w{0,50})/$', views.details, name="details"),
    url(r'^update', views.update, name="update"),
    url(r'^add', views.add, name="add"),
]

todo/models.py
from django.db import models
from datetime import datetime

class Task(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    date_added = models.DateField(default=datetime.now)
    slug = models.CharField(max_length=500)
    finished = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from . import models

class AddTask(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ['name','description','date_added', 'finished', 'slug']
        labels = {
            'name':'Name','description':'Description','date_added':'Date Added', 'finished':'Finished', 'slug':'Slug'
        }
        widgets = {
            'finished' : forms.CheckboxInput(attrs={'class': 'finished-cb', 'id':'id_finished', 'name':'finished'})
        }        
            

todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Task
from . import forms

def index(request):
    tasks = Task.objects.all()[:10]
    context={
        'tasks':tasks
    }
    return render(request, 'index.html', context)

def details(request, id):
    task = Task.objects.get(id=id)
    context={
        'task':task
    }
    return render(request, 'details.html', context)

def add(request):
    if(request.method == 'POST'):
        form = forms.AddTask(request.POST, request.FILES)
        if form.is_valid():
            task = form.save(commit=False)
            task.save()

            return redirect('/todo')
    else:
        form = forms.AddTask()
        return render(request, 'add.html', {'form':form})

def update(request):
    id = request.POST.get('task_id')
    if request.POST.get('finished'):
        val = 1
    else:
        val = 0
    print('val :' + str(val))
    task = Task.objects.filter(pk=id).update(finished=bool(val))
    return redirect('/todo')

todo/templates/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>Add Task</title>
</head>
<body>
    <h1>Add New Task</h1>
    <form class="site-form" action="{% url 'todo:add' %}" method="post">
        {% csrf_token %}
        {{form}}
        <br> 
        <input type="submit" value="Add Task"/>
    </form>
    <a href="/todo">Go Back</a>
    <script src="/static/js/slugify.js"></script>
</body>
</html>

todo/templates/details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>Details</title>
</head>
<body>
    <a href="/todo">Go Back</a>
    {% if task.finished %}
        <form class="site-form details task-finished" action="{% url 'todo:update' %}" method="post">
    {% else %}
        <form class="site-form details" action="{% url 'todo:update' %}" method="post">
    {%endif%}    
    <!-- <div class="site-form details">         -->
        <br>
        <h1>
            {{task.name}}
        </h1>
        <p>
            {{task.description}}
        </p>
        {{task.date_added}}
        <p>{{task.slug}}</p>
        
        {% if task.finished %}
            <p>Completed!</p>
        {% else %}
            <p>In Progress</p>
        {%endif%}
    </div>
</body>
</html>

todo/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>Todo's</title>
</head>
<body>
    <h1>Todos</h1>
    {% for task in tasks %}
        {% if task.finished %}
            <form class="site-form task-finished" action="{% url 'todo:update' %}" method="post">
        {% else %}
            <form class="site-form" action="{% url 'todo:update' %}" method="post">
        {%endif%}
            {% csrf_token %}
            <input type="hidden" name="task_id" id="task_id" value={{task.id}}>
            <li>
                <a href="/todo/details/{{task.id}}">{{task.name}}  </a> {{task.description}}
                {% if task.finished %}
                    <input type="checkbox" name="finished" id="finished_{{task.id}}" value=1 checked disabled>
                    <input type="hidden" name="cb_val" id="task_id" value=True disabled>
                    <input type="submit" value="Update" disabled>
                {% else %}
                    <input type="checkbox" name="finished" id="finished_{{task.id}}" value=0>
                    <input type="hidden" name="cb_val" id="task_id" value=False>
                    <input type="submit" value="Update">
                {% endif %}
                
            </li>        
        </form>
    {% endfor %}
    <h1><a href="/todo/add">Add Task</a></h1>
</body>
</html>